version: "3.3"

services:
  nginx:
    image: nginx
    container_name: nginx-container
    expose:
      - 80/tcp
    ports:
      - 80:80
    restart: always
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/laravel:ro
    depends_on:
      - php
      - mysql
      - phpmyadmin
    networks:
      - laravel-network

  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    container_name: php-container
    restart: always
    volumes:
      - ./:/var/www/laravel
    networks:
      - laravel-network

  mysql:
    image: mysql
    container_name: mysql-container
    expose:
      - 3306/tcp
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    expose:
      - 80/tcp
    ports:
      - 8080:80
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    name: laravel-network
    driver: bridge
